//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BattleShip
{
    using System;
    using System.Collections.Generic;
    
    public partial class game
    {
        public long game_id { get; set; }
        public long player1_id { get; set; }
        public long player2_id { get; set; }
        public bool player1win { get; set; }
        public bool player2win { get; set; }
        public bool draw { get; set; }
    
        public virtual player player { get; set; }
        public virtual player player1 { get; set; }
    }
}
